version: '3.8'

services:
  mongoDB:
    container_name: ${APP_PREFIX}-mongoDB
    image: mongo:4.4.3
    volumes:
      - ./server/data:/data/
      - ./server/logs/db:/usr/src/app/logs/db/
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    command:
      ['--logpath', '/usr/src/app/logs/db/logs.log', '--logappend', '--quiet']
    networks:
      - webnet

  server:
    container_name: ${APP_PREFIX}-server
    image: referrer-tracker:latest
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    command: yarn run dev
    restart: on-failure
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongoDB

  web-client:
    container_name: ${APP_PREFIX}-client
    image: ${APP_PREFIX}-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    restart: on-failure
    command: yarn run serve
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - mongoDB
      - server
networks:
  webnet:
